### ISSUE TITLE
Создание итогового отчёта

### ISSUE THREAD

**Issue by Kiruha01** [PracticeProject21/CoreAnalysis#72]
Составить отчёт о пройденной учебной практике, согласно требованиям, опубликованным в MS Teams

**Comment by AnatolyAdamovich** [comment]
Отчет по каждой части должен иметь структуру:
1. Список используемых технологий с описанием, для чего использовали.
2. Описание, как шла работа над проектом, какие стадии прошли.
3. Описание полученного результата.
4. Список фичей, которые можно было бы добавить при наличии дополнительного времени.
